### ISSUE TITLE
awx.awx.schedule_rruleset error

### ISSUE THREAD

**Issue by npithonDR** [ansible/awx#13446]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Hello,

I tried to use awx.awx.schedule_rruleset module but i have an error:
```
  File "/runner/requirements_collections/ansible_collections/awx/awx/plugins/lookup/schedule_rruleset.py", line 268, in run
    if frequency not in self.frequencies:
AttributeError: 'LookupModule' object has no attribute 'frequencies'
```

My task:
```
    - name: Build a complex schedule for every day except sunday using the rruleset plugin
      awx.awx.schedule:
        name: "Template job"
        state: present
        unified_job_template: "Demo Job Template"
        rrule: "{{ query('awx.awx.schedule_rruleset', '2023-04-30 10:30:45', rules=rrules, timezone='UTC' ) }}"
      vars:
        rrules:
          - frequency: 'day'
            interval: 1
```

AWX version:  21.10.2

### AWX version

21.10.2

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

quay.io/ansible/ansible-runner:stable-2.12-latest

### Web browser

Firefox, Chrome

### Steps to reproduce

Create playbook:
```
---
- name: Configure AWX bankess settings
  hosts: localhost
  run_once: true
  become: false
  gather_facts: false

  vars:
    ansible_connection: local
    controller_host: "http://CONTROLLER_IP"
    awx_username: admin
    awx_password: "adminawxpassword"
    ansible_connection: local

  environment:
    TOWER_USERNAME: "{{ awx_username | mandatory }}"
    TOWER_PASSWORD: "{{ awx_password | mandatory }}"
    TOWER_HOST: "{{ controller_host | mandatory }}"
    TOWER_VERIFY_SSL: "false"

  tasks:
    - name: install dateutil
      ansible.builtin.pip:
        name: python-dateutil

    - name: Build a complex schedule for every day except sunday using the rruleset plugin
      awx.awx.schedule:
        name: "Template job"
        state: present
        unified_job_template: "Demo Job Template"
        rrule: "{{ query('awx.awx.schedule_rruleset', '2023-04-30 10:30:45', rules=rrules, timezone='UTC' ) }}"
      vars:
        rrules:
          - frequency: 'day'
            interval: 1
```

### Expected results

Schedule created without error in ansible

### Actual results

```
exception during Jinja2 execution: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ansible/template/__init__.py", line 1032, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
  File "/runner/requirements_collections/ansible_collections/awx/awx/plugins/lookup/schedule_rruleset.py", line 268, in run
    if frequency not in self.frequencies:
AttributeError: 'LookupModule' object has no attribute 'frequencies'
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'awx.awx.schedule_rruleset'. Error was a <class 'AttributeError'>, original message: 'LookupModule' object has no attribute 'frequencies'. 'LookupModule' object has no attribute 'frequencies'"
}
```

### Additional information

Use collection:
```
---
collections:
  - name: awx.awx
    version: 21.10.2
```

The AWX job execution env use the docker image: `quay.io/ansible/ansible-runner:stable-2.12-latest`

**Comment by AlanCoding** [comment]
I was able to run your playbook and reproduce the error. This seems to be somewhat obviously introduced in https://github.com/ansible/awx/pull/13238

**Comment by npithonDR** [comment]
Hello,
I tested the devel branch and it's ok with this exemple. Thanks

But if I test with this vars:
```
      vars:
        rrules:
          - frequency: 'day'
            interval: 1
            byweekday: 'sunday'
```

I have this error:
```
{
  "msg": "An unhandled exception occurred while running the lookup plugin 'awx.awx.schedule_rruleset'. Error was a <class 'ansible.errors.AnsibleError'>, original message: In rule 1 byweekday must only contain values in monday, tuesday, wednesday, thursday, friday, saturday, sunday. In rule 1 byweekday must only contain values in monday, tuesday, wednesday, thursday, friday, saturday, sunday",
  "_ansible_no_log": false
}
```

Best Regards
