### PR TITLE
Fix DevOps Secrets Vault credential plugin

### PR DESCRIPTION
**Pull request by andrii-zakurenyi**
##### SUMMARY

Fix Delinea (previously: Thycotic) DevOps Secrets Vault credential plugin to work with `python-dsv-sdk>=1.0.4`.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API (Credential Plugin)

##### AWX VERSION

```
awx: 23.3.1.dev6+ge753723217
```

##### ADDITIONAL INFORMATION

I'll update the name from Thycotic to Delinea in a separate change.

### CODE REVIEW

**Comment by fosterseth** [comment]
the name change PR is already opened https://github.com/ansible/awx/pull/14207/files

**Comment by fosterseth** [comment]
Can you provide details about the errors you were getting before the changes you made?

in our PR that upgrades to python 3.11, we pinned the sdk to 1.0.1 which fixed the unit tests. https://github.com/ansible/awx/pull/14257/files#diff-2d88edd924033b49783dcb4f93a0ed0ec8aae0b6aac3bad984a2c1d323b93c37R44

**Comment by andrii-zakurenyi** [comment]
> the name change PR is already opened https://github.com/ansible/awx/pull/14207/files

That PR is about Secret Server which is an another product from Delinea.
This PR is about DevOps Secrets Vault (DSV) and I plan to change name for DSV credential plugin.

**Comment by andrii-zakurenyi** [comment]
> Can you provide details about the errors you were getting before the changes you made?
> 
> in our PR that upgrades to python 3.11, we pinned the sdk to 1.0.1 which fixed the unit tests. https://github.com/ansible/awx/pull/14257/files#diff-2d88edd924033b49783dcb4f93a0ed0ec8aae0b6aac3bad984a2c1d323b93c37R44

I see "TypeError" when I try to test credential with type "Thycotic DevOps Secrets Vault".

image

I can get the same "TypeError" locally when I use sdk `1.0.1` as if it was `0.0.1`:

```
$ python3                   
Python 3.8.10 (default, May 26 2023, 14:05:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from thycotic.secrets.vault import SecretsVault
>>> SecretsVault(
...   tenant='***hidden***',
...   tld='com',
...   client_id='***hidden***',
...   client_secret='***hidden***',
... ).get_secret('ansible-secrets:first')['data']['access_key']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'tenant'
>>> 
```

Current implementation of credential plugin was written specifically for `python-dsv-sdk==0.0.1` where in `__init__` for `SecretsVault` class you need to provide info related to authentication:

https://github.com/DelineaXPM/python-dsv-sdk/blob/v0.0.1/thycotic/secrets/vault.py#L137

hence current code does:
```python
lambda **kwargs: SecretsVault(**{k: v for (k, v) in kwargs.items()...
```

And I change it to actually work with version `1.0.1` in which `__init__` method for `SecretsVault` class now requires a special authorizer which is able to return an access token to DSV:

https://github.com/DelineaXPM/python-dsv-sdk/blob/v1.0.1/thycotic/secrets/vault.py#L214

hence changed code does:

```python
SecretsVault(tenant_url, authorizer)
```

**Comment by rebeccahhh** [comment]
We've got an upgrade coming in for delinea (https://github.com/ansible/awx/pull/14362) so once those are in you'll probably need to rebase.

**Comment by andrii-zakurenyi** [comment]
> We've got an upgrade coming in for delinea (#14362) so once those are in you'll probably need to rebase.

Thank you for letting me know.

**Comment by jessicamack** [comment]
@andrii-zakurenyi thank you for your contribution. #14362 has been merged so you can rebase now.

**Comment by andrii-zakurenyi** [comment]
I've executed:
```
$ black ./awx/main/credential_plugins/dsv.py 
```
and this was the output:

```
reformatted awx/main/credential_plugins/dsv.py

All done! ✨ 🍰 ✨
1 file reformatted.
```

I hope it helps with the "api-lint" check.

**Review by fosterseth — APPROVED** [review]
