### ISSUE TITLE
21.14.0: Blank webui with German browser: Uncaught (in promise) Error: Cannot find module './de/messages'

### ISSUE THREAD

**Issue by Commifreak** [ansible/awx#13756]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

After setup current operator and restore a previous backup, the awx web-ui raises an JS error inside Firefox (and Chrome):

```
Uncaught (in promise) Error: Cannot find module './de/messages'
    i |groupOptions: {}|namespace object:38
    promise callback*i |groupOptions: {}|namespace object:37
    e i18nLoader.js:31
    u runtime.js:63
    _invoke runtime.js:294
    k runtime.js:119
    Babel 4
    KU i18nLoader.js:47
    Vve i18nLoader.js:30
    Vve App.js:149
    Fl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    M scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    6813 scheduler.production.min.js:12
    Webpack 10
[|groupOptions: {}|namespace object:38:11](http://172.31.10.16/static/js/locales|lazy|/%5E//.*//messages$/|groupOptions:%20%7B%7D|namespace%20object)
    Babel 6
    KU i18nLoader.js:47
    Vve i18nLoader.js:30
    Vve App.js:149
    Fl React
    unstable_runWithPriority scheduler.production.min.js:18
    React 3
    M scheduler.production.min.js:16
    onmessage scheduler.production.min.js:12
    (Async: EventHandlerNonNull)
    6813 scheduler.production.min.js:12
    Webpack 10
```

### AWX version

21.14.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Operating system

Ubuntu 22.04

### Web browser

Firefox, Chrome

### Steps to reproduce

Setup operator, restore backup

### Expected results

functional webui

### Actual results

Blank page with described JS error

**Comment by Commifreak** [comment]
A fresh install ends up in the same result :/

**Comment by kurokobo** [comment]
Confirmed that this can be easily reproduced by changing browser's language to German.
As a workaround changing it to English.

**Comment by Commifreak** [comment]
Wow. Okay, then I downgrade, switching language is no solution for now. Thanks for confirmation.

**Comment by Commifreak** [comment]
Downgrade to AWX 21.13.0 solves the issue for now.

**Comment by kurokobo** [comment]
@mabashian 
I haven't looked into this enough, but is there any possibility that the ability to fall back to English have broken when no translation exists for the browser's language by https://github.com/ansible/awx/commit/7f1750324fb4144298f70aba3ca763ef6ac615e0 or some commit?

**Comment by MaximilianMeister** [comment]
Same error message here (`Uncaught (in promise) Error: Cannot find module './de/messages'`) on an upgraded instance of AWX, **but** my browser is set to EN, not to DE

So I can not confirm that switching the Browser language to EN fixes it, trying to downgrade to `21.13.0` now

**Comment by BRE-MD** [comment]
I can confirm that after update 21.13.0 to 21.14.0 or changing the browser language, the cache needs to be cleaned for anything to change.

**Comment by tanganellilore** [comment]
Hi,
i have the same issue and I opened a PR to fix it.
You can workaround it with one of the following solution in the meantime:
- change your browser language to en (restart the browser)
- add at the end of url `?lang=en`

Some changes was made on https://github.com/ansible/awx/pull/13661 that broke this.

I hope that my pull request will be approved.

**Comment by TerranMan** [comment]
Same bug with Russian browser language - just blank page.  
adding `?lang=en` fixes it, thanks @tanganellilore

**Comment by BRE-MD** [comment]
I can confirm, same issue in AWX 22.0.0.

**Comment by sevko21** [comment]
I can also confirm. Same issue with AWX 22.0.0.

**Comment by AlePini** [comment]
I also confirm this issue. With italian language just blank page with error:
`Uncaught (in promise) Error: Cannot find module './it/messages'`
It's appening since release AWX 21.4.0

**Comment by achhetri** [comment]
Conformed also for Version : Ansible AWX 22.0.1.dev0+g2db29e5ce2.d20230410

![image](https://user-images.githubusercontent.com/10814481/231073435-269be6b9-3a35-4f22-85a6-850028f45929.png)

**Comment by mabashian** [comment]
Hey yall - thanks for all the info here.  The problem is that this logic: https://github.com/ansible/awx/pull/13661/files#diff-9aa9ae24f77a4023dd6384ed03db2e9023920284a5da439ffa13b06f68c5540cL143-L147 got dropped in my changes so if your browser is set to a language that we don't have translations for then you'll see the above error.  @tanganellilore thanks for opening up your pull request - that would technically fix the issue for folks who have their language set to `it` but won't catch other languages without translations.  I'll open up a PR to address this shortly.  As you've all pointed out, you can use the newly added `lang` query param to get around this.

**Comment by mabashian** [comment]
https://github.com/ansible/awx/pull/13832 I think this is the fix we need.  @tanganellilore your PR is still very relevant and is much appreciated!

**Comment by tanganellilore** [comment]
yes, https://github.com/ansible/awx/pull/13766 fix this for all languages 😄 .
Other PR is for add new language, taht is not under this issue.

So i think we can close this issue and other opened for the same things.
Thanks

**Comment by mabashian** [comment]
@tanganellilore I'm so sorry - I didn't see your other PR!  I'll close mine out and approve yours 🎉

**Comment by mabashian** [comment]
Fixed with https://github.com/ansible/awx/pull/13766 🎉
