### ISSUE TITLE
Openshift AWX installer does not work with oc version 4.2 

### ISSUE THREAD

**Issue by bharathvenkatrajan** [ansible/awx#7053]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
I am following the documentation to install awx in openshift https://github.com/ansible/awx/blob/devel/INSTALL.md. The steps are under `Openshift install steps`.

When I update the inventory file and run `ansible-playbook -i inventory install.yml` I get the following error in Task `TASK [kubernetes : Use correct cli option for kubeconfig]` (please refer to the step [here](https://github.com/ansible/awx/search?q=Use%20correct%20cli%20option%20for%20kubeconfig&unscoped_q=Use%20correct%20cli%20option%20for%20kubeconfig))

ERROR:
`fatal: [localhost]: FAILED! => {"msg": "Version comparison: LooseVersion instance has no attribute 'version'"}`

Using ansible version: 

```
ansible 2.9.7
    config file = /etc/ansible/ansible.cfg
    configured module search path = [u'/root/.ansible/plugins/modules', 
    u'/usr/share/ansible/plugins/modules']
    ansible python module location = /usr/lib/python2.7/site-packages/ansible
    executable location = /bin/ansible
    python version = 2.7.5
```

##### ENVIRONMENT
* AWX version: latest
* AWX install method: openshift
* Ansible version:  2.9.7
* Operating System: CentOS
* Web Browser: Google chrome
* oc version
    * Client Version: openshift-clients-4.2
    * Server Version: 4.2
    * Kubernetes Version: v1.14.6

##### STEPS TO REPRODUCE

* Install ansible 2.9.7
* git clone the AWX repo and edit the inventory file like below:

Inventory file: Make the following changes to the openshift install part
```
#Openshift Install
#Will need to set -e openshift_password=developer -e docker_registry_password=$(oc whoami -t)
#or set -e openshift_token=TOKEN

openshift_host=console-openshift-console.apps.my.server.com:443
openshift_project=awx
openshift_user=xxxxx
openshift_password=xxxxx
openshift_skip_tls_verify=True

# openshift_pg_emptydir=True
```

##### EXPECTED RESULTS

Expected the installer to deploy a postgres instance and AWX instance in Openshift.

##### ACTUAL RESULTS
Fails at [step](https://github.com/ansible/awx/search?q=Use+correct+cli+option+for+kubeconfig&unscoped_q=Use+correct+cli+option+for+kubeconfig) Use correct cli option for kubeconfig". 
```
ERROR:
`fatal: [localhost]: FAILED! => {"msg": "Version comparison: LooseVersion instance has no attribute 'version'"}`
```
##### ADDITIONAL INFORMATION

The shell command in the previous [step](https://github.com/ansible/awx/search?q=sed+-n+%27s%2Foc+v%2F%2Fp%27&unscoped_q=sed+-n+%27s%2Foc+v%2F%2Fp%27) 

Shell command ```oc version | sed 's/oc v//p'``` gives me:

````
Client Version: openshift-clients-4.2.0
Server Version: 4.2.16
Kubernetes Version: v1.14.6
````

UPDATE: As a workaround I hard-coded the [step](https://github.com/ansible/awx/search?q=Use+correct+cli+option+for+kubeconfig&unscoped_q=Use+correct+cli+option+for+kubeconfig) to use `--kubeconfig` since I know my oc version is 4.2 (above 3.11)  and I was able to deploy awx successfully.

**Comment by shanemcd** [comment]
Ugh, sorry about that. I assumed since the 3.11 client matches the formatting in 4.3 and 4.4 that 4.2 would work too. That said, I'm inclined not to fix this since 4.2 EOL'd back in February.

**Comment by shanemcd** [comment]
Actually... fixed by https://github.com/ansible/awx/pull/7189

**Comment by bharathvenkatrajan** [comment]
Thank you!
