### ISSUE TITLE
AWX 21.12 ldap team mapping broken

### ISSUE THREAD

**Issue by CWollinger** [ansible/awx#13614]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

The LDAP team mapping is not working in AWX 21.12. 

Users are not mapped and associated with the team belonging to the LDAP group. Organization map works fine.

Using MemberDNGroupType

### AWX version

21.12.0

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

minikube

### Modifications

no

### Steps to reproduce

- Create LDAP user (uid=test@ldap,ou=users,dc=example,dc=org)
- Create user role (cn=userrole,ou=roles,dc=example,dc=org)
- Configure LDAP Team Map

````
{
  "Demo Team": {
    "organization": "Demo",
    "remove": true,
    "users": "cn=userrole,ou=roles,dc=example,dc=org"
  }
}
````

### Expected results

- If not exists, team `Demo Team` created
- User `test@ldap` is member of the team

### Actual results

- Team is not created
- User is not a member of the team
- User is member of the org.

### Additional information

Team map works fine in AWX 21.11.

**Comment by CWollinger** [comment]
maybe related to https://github.com/ansible/awx/pull/13430 ?

**Comment by john-westcott-iv** [comment]
This should be fixed by https://github.com/ansible/awx/pull/13573 and will be released in the next version of AWX.

**Comment by bandwiches** [comment]
DANG! I just battled all afternoon with this issue due to my failure to realize I was searching issues in the wrong repo.  Looking forward to the fix in the next version

**Comment by fosterseth** [comment]
note: we can close this after next release

**Comment by CWollinger** [comment]
Confirm the fix in AWX 21.13
