### ISSUE TITLE
Job failed if Job Slicing and Fact Storage enabled together

### ISSUE THREAD

**Issue by lutskevich** [ansible/awx#13131]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Job failed if Job Slicing and Fact Storage enabled together

`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 504, in run
    self.instance.start_job_fact_cache(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/jobs.py", line 862, in start_job_fact_cache
    hosts = hosts.filter(ansible_facts_modified__gte=timeout)
AttributeError: 'list' object has no attribute 'filter'`

### AWX version

AWX 21.7.0  

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

1. Create Job Template. 
2. Make sure the Job Slicing >2.
3. Enable Enable Fact Storage flag
4. Launch job 

### Expected results

Job is done

### Actual results

Job failed with error:
`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/tasks/jobs.py", line 504, in run
    self.instance.start_job_fact_cache(
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/main/models/jobs.py", line 862, in start_job_fact_cache
    hosts = hosts.filter(ansible_facts_modified__gte=timeout)
AttributeError: 'list' object has no attribute 'filter'`

**Comment by AlanCoding** [comment]
I confirmed I can reproduce this error. Doing so requires modifying the setting `ANSIBLE_FACT_CACHE_TIMEOUT` to a value greater than zero, @relrod we may need to evaluate the extent of the fallout if this was introduced in https://github.com/ansible/awx/pull/12790 I think the root of the problem is that a slice will return a list, not a queryset.

I also confirmed that this is fixed in https://github.com/ansible/awx/pull/12998, so I don't want to dive into a separate AWX patch just for this bug.

**Comment by relrod** [comment]
> I think the root of the problem is that a slice will return a list, not a queryset.

Yep. Per Django docs:

>  Slicing an unevaluated `QuerySet` usually returns another unevaluated `QuerySet`, but Django will execute the database query if you use the “step” parameter of slice syntax, and will return a list.

I did not realize that was a special case (but it makes sense since it probably can't do the step part as part of the query). Ugh. :(

**Comment by relrod** [comment]
Also, thanks for this report @lutskevich

**Comment by jay-steurer** [comment]
Issue fixed. PR merged. Closing it.
